### ISSUE TITLE
Why SystemCoreClockUpdate did not supports RCC_CFGR_SWS_HSI48

### ISSUE THREAD

**Issue by canmor** [STMicroelectronics/cmsis_device_f0#1] opened 2022-11-11 08:20 UTC
HSI48 could be select as system clock, why this case is not support by SystemCoreClockUpdate?

**Comment by ASELSTM** [comment] 2022-11-21 11:25
Hi @canmor,

Please allow me to close this thread as it is a duplicate of #2 .

With regards,

**Closed as not planned by ASELSTM** 2022-11-21 11:25 UTC
Labels: duplicate, cmsis
